A few utility functions for preapring training data of deep nerual network models for the retail sales forecasting problem

In [1]:
import os
import sys
import math
import itertools
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Append TSPerf path to sys.path
nb_dir = os.path.split(os.getcwd())[0]
tsperf_dir = os.path.dirname(os.path.dirname(nb_dir))
if tsperf_dir not in sys.path:
    sys.path.append(tsperf_dir)

import retail_sales.OrangeJuice_Pt_3Weeks_Weekly.common.benchmark_settings as bs

In [3]:
# Data paths
DATA_DIR = '../data'
TRAIN_DIR = os.path.join(DATA_DIR, 'train')

# Parameters of the model
PRED_HORIZON = 3
PRED_STEPS = 2
SEQ_LEN = 8

## DNN Utility Functions

In [4]:
def df_from_cartesian_product(dict_in):
    """Generate a Pandas dataframe from Cartesian product of lists.
    
    Args: 
        dict_in (Dictionary): Dictionary containing multiple lists
        
    Returns:
        df (Dataframe): Dataframe corresponding to the Caresian product of the lists
    """
    from collections import OrderedDict
    from itertools import product
    od = OrderedDict(sorted(dict_in.items()))
    cart = list(product(*od.values()))
    df = pd.DataFrame(cart, columns=od.keys())
    return df

def gen_sequence(df, seq_len, seq_cols, start_timestep=0, end_timestep=None):
    """Reshape features into an array of dimension (time steps, features)   
    
    Args:
        df (Dataframe): Time series data of a specific (store, brand) combination
        seq_len (Integer): The number of previous time series values to use as input features
        seq_cols (List): A list of names of the feature columns 
        start_timestep (Integer): First time step you can use to create feature sequences
        end_timestep (Integer): Last time step you can use to create feature sequences
        
    Returns:
        A generator object for iterating all the feature sequences
    """
    data_array = df[seq_cols].values
    if end_timestep is None:
        end_timestep = df.shape[0]
    for start, stop in zip(range(start_timestep, end_timestep-seq_len+2), range(start_timestep+seq_len, end_timestep+2)):
        yield data_array[start:stop, :]
        
def gen_sequence_array(df_all, seq_len, seq_cols, start_timestep=0, end_timestep=None):
    """Combine feature sequences for all the combinations of (store, brand) into an 3d array.
    
    Args:
        df_all (Dataframe): Time series data of all stores and brands
        seq_len (Integer): The number of previous time series values to use as input features
        seq_cols (List): A list of names of the feature columns 
        start_timestep (Integer): First time step you can use to create feature sequences
        end_timestep (Integer): Last time step you can use to create feature sequences
        
    Returns:
        seq_array (Numpy Array): An array of the feature sequences of all stores and brands    
    """
    seq_gen = (list(gen_sequence(df_all[(df_all['store']==cur_store) & (df_all['brand']==cur_brand)], \
                                 seq_len, seq_cols, start_timestep, end_timestep)) \
              for cur_store, cur_brand in itertools.product(df_all['store'].unique(), df_all['brand'].unique()))
    seq_array = np.concatenate(list(seq_gen)).astype(np.float32)
    return seq_array

def static_feature_array(df_all, total_timesteps, seq_cols):
    """Generate an arary which encodes all the static features.
    
    Args:
        df_all (Dataframe): Time series data of all stores and brands
        total_timesteps (Integer): Total number of training samples for each store and brand
        seq_cols (List): A list of names of the static feature columns (e.g., store index)
        
    Returns:
        fea_array (Numpy Array): An array of static features of all stores and brands
    """
    fea_df = data_filled.groupby(['store', 'brand']). \
                         apply(lambda x: x.iloc[:total_timesteps,:]). \
                         reset_index(drop=True)
    fea_array = fea_df[seq_cols].values
    return fea_array

def normalize_dataframe(df, seq_cols, scaler=MinMaxScaler()):
    """Normalize a subset of columns of a dataframe.
    
    Args:
        df (Dataframe): Input dataframe 
        seq_cols (List): A list of names of columns to be normalized
        scaler (Scaler): A scikit learn scaler object
    
    Returns:
        df_scaled (Dataframe): Normalized dataframe
    """
    cols_fixed = df.columns.difference(seq_cols)
    df_scaled = pd.DataFrame(scaler.fit_transform(df[seq_cols]), 
                            columns=seq_cols, index=df.index)
    df_scaled = pd.concat([df[cols_fixed], df_scaled], axis=1)
    return df_scaled, scaler

## Test the funtions

In [5]:
r = 0
print('---- Round ' + str(r+1) + ' ----')
# Load training data
train_df = pd.read_csv(os.path.join(TRAIN_DIR, 'train_round_'+str(r+1)+'.csv'))
train_df['move'] = train_df['logmove'].apply(lambda x: round(math.exp(x)))
train_df.drop('logmove', axis=1, inplace=True)
print(train_df.head(3))
# Fill missing values
store_list = train_df['store'].unique()
brand_list = train_df['brand'].unique()
week_list = range(bs.TRAIN_START_WEEK, bs.TEST_END_WEEK_LIST[r]+1)
d = {'store': store_list,
     'brand': brand_list,
     'week': week_list}        
data_grid = df_from_cartesian_product(d)
data_filled = pd.merge(data_grid, train_df, how='left', 
                        on=['store', 'brand', 'week'])
print('Number of missing rows is {}'.format(data_filled[data_filled.isnull().any(axis=1)].shape[0]))
data_filled = data_filled.groupby(['store', 'brand']). \
                          apply(lambda x: x.fillna(method='ffill').fillna(method='bfill'))
print(data_filled.head(3))
# Select subset of the data
data_sub = data_filled[(data_filled.brand==1) & (data_filled.store==2)]
print(data_sub[['store', 'brand', 'week', 'deal', 'feat', 'move']])

---- Round 1 ----
   store  brand  week  constant    price1    price2    price3    price4  \
0      2      1    40         1  0.060469  0.060497  0.042031  0.029531   
1      2      1    46         1  0.060469  0.060312  0.045156  0.046719   
2      2      1    47         1  0.060469  0.060312  0.045156  0.046719   

     price5    price6    price7    price8    price9   price10   price11  deal  \
0  0.049531  0.053021  0.038906  0.041406  0.028906  0.024844  0.038984     1   
1  0.049531  0.047813  0.045781  0.027969  0.042969  0.042031  0.038984     0   
2  0.037344  0.053021  0.045781  0.041406  0.048125  0.032656  0.038984     0   

   feat     profit  move  
0   0.0  37.992326  8256  
1   0.0  30.126667  6144  
2   0.0  30.000000  3840  
Number of missing rows is 6204
   brand  store  week  constant    price1    price2    price3    price4  \
0      1      2    40       1.0  0.060469  0.060497  0.042031  0.029531   
1      1      2    41       1.0  0.060469  0.060497  0.042031  0.02

In [6]:
# Create feature sequence array based on data_sub
start_timestep = 0
end_timestep = bs.TRAIN_END_WEEK_LIST[r]-bs.TRAIN_START_WEEK-PRED_HORIZON
train_input1 = gen_sequence_array(data_sub, SEQ_LEN, ['move'], start_timestep, end_timestep)
train_input1.shape

(86, 8, 1)

In [7]:
train_input1

array([[[ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 6144.],
        [ 3840.]],

       [[ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 6144.],
        [ 3840.],
        [ 8000.]],

       [[ 8256.],
        [ 8256.],
        [ 8256.],
        [ 8256.],
        [ 6144.],
        [ 3840.],
        [ 8000.],
        [ 8000.]],

       [[ 8256.],
        [ 8256.],
        [ 8256.],
        [ 6144.],
        [ 3840.],
        [ 8000.],
        [ 8000.],
        [ 8896.]],

       [[ 8256.],
        [ 8256.],
        [ 6144.],
        [ 3840.],
        [ 8000.],
        [ 8000.],
        [ 8896.],
        [ 7168.]],

       [[ 8256.],
        [ 6144.],
        [ 3840.],
        [ 8000.],
        [ 8000.],
        [ 8896.],
        [ 7168.],
        [10880.]],

       [[ 6144.],
        [ 3840.],
        [ 8000.],
        [ 8000.],
        [ 8896.],
        [ 7168.],
        [10880.]

In [8]:
# Create feature sequence array based on data_filled
%time
train_input1 = gen_sequence_array(data_filled, SEQ_LEN, ['move'], start_timestep, end_timestep)
train_input1.shape

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 6.91 µs


(78518, 8, 1)

In [9]:
# Create array of static features 
total_timesteps = bs.TRAIN_END_WEEK_LIST[r]-bs.TRAIN_START_WEEK-SEQ_LEN-PRED_HORIZON+2
train_input2 = static_feature_array(data_filled, total_timesteps, ['store', 'brand'])
train_input2.shape

(78518, 2)

In [10]:
train_input2

array([[  2,   1],
       [  2,   1],
       [  2,   1],
       ...,
       [137,  11],
       [137,  11],
       [137,  11]])

In [11]:
# Test scaler
df_scaled, scaler = normalize_dataframe(data_sub[['store', 'brand', 'week', 'profit', 'move']], ['profit', 'move'])
df_scaled

brand  store  week    profit      move
0       1      2    40  0.730845  0.115086
1       1      2    41  0.730845  0.115086
2       1      2    42  0.730845  0.115086
3       1      2    43  0.730845  0.115086
4       1      2    44  0.730845  0.115086
5       1      2    45  0.730845  0.115086
6       1      2    46  0.572949  0.063764
7       1      2    47  0.570406  0.007776
8       1      2    48  0.569402  0.108865
9       1      2    49  0.569402  0.108865
10      1      2    50  0.568800  0.130638
11      1      2    51  0.568800  0.088647
12      1      2    52  0.512702  0.178849
13      1      2    53  0.512694  0.102644
14      1      2    54  0.511839  0.121306
15      1      2    55  0.511839  0.121306
16      1      2    56  0.511839  0.121306
17      1      2    57  0.511412  0.048212
18      1      2    58  0.560792  0.057543
19      1      2    59  0.596498  0.118196
20      1      2    60  0.597023  0.059098
21      1      2    61  0.598909  0.080871
22      1      2    62  0.638390  0.138414
23      1      2    63  0.364245  0.209953
24      1      2    64  0.410634  0.222395
25      1      2    65  0.677866  0.073095
26      1      2    66  0.675143  0.063764
27      1      2    67  0.471775  0.427683
28      1      2    68  0.310849  0.216174
29      1      2    69  0.850611  0.144635
..    ...    ...   ...       ...       ...
69      1      2   109  0.589276  0.079316
70      1      2   110  0.598082  0.079316
71      1      2   111  0.596343  0.066874
72      1      2   112  0.592033  0.043546
73      1      2   113  0.629964  0.138414
74      1      2   114  0.779043  0.091757
75      1      2   115  0.224150  0.746501
76      1      2   116  0.699999  0.088647
77      1      2   117  0.921452  0.062208
78      1      2   118  0.921465  0.038880
79      1      2   119  0.748704  0.116641
80      1      2   120  0.568654  0.345257
81      1      2   121  0.534899  0.233281
82      1      2   122  0.448228  0.233281
83      1      2   123  0.485839  0.152411
84      1      2   124  0.843119  0.000000
85      1      2   125  0.843050  0.048212
86      1      2   126  0.887960  0.077760
87      1      2   127  0.363753  0.405910
88      1      2   128  0.970064  0.037325
89      1      2   129  0.363768  0.973561
90      1      2   130  0.183865  0.539658
91      1      2   131  0.101531  0.687403
92      1      2   132  0.185096  0.418351
93      1      2   133  0.459738  0.283048
94      1      2   134  0.273309  0.597201
95      1      2   135  0.327826  0.216174
96      1      2   136  0.327826  0.216174
97      1      2   137  0.327826  0.216174
98      1      2   138  0.327826  0.216174

[99 rows x 5 columns]

In [12]:
print('Minimum move after scaling is {}'.format(min(df_scaled['move'])))
print('Maximum move after scaling is {}'.format(max(df_scaled['move'])))

Minimum move after scaling is 0.0
Maximum move after scaling is 1.0


In [13]:
scaler.data_range_

array([   49.81538462, 41152.        ])